from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agentos_orchestrator.os_control.workflow.models import (
    DesktopWorkflowPlan,
    WorkflowArtifact,
)


class WorkflowArtifactWriter:
    def __init__(self, workspace_root: str | Path) -> None:
        self.workspace_root = Path(workspace_root)

    def materialize(
        self,
        plan: DesktopWorkflowPlan,
        *,
        skip_paths: set[str] | None = None,
    ) -> list[dict[str, Any]]:
        written: list[dict[str, Any]] = []
        skipped = {str(path) for path in (skip_paths or set())}
        for artifact in plan.artifacts:
            if artifact.path in skipped:
                continue
            path = self.workspace_root / artifact.path
            path.parent.mkdir(parents=True, exist_ok=True)
            content = self._artifact_content(plan, artifact)
            path.write_text(content, encoding="utf-8")
            written.append(
                {
                    "path": artifact.path,
                    "kind": artifact.kind,
                    "description": artifact.description,
                    "bytes": len(content.encode("utf-8")),
                }
            )
        return written

    def _artifact_content(
        self,
        plan: DesktopWorkflowPlan,
        artifact: WorkflowArtifact,
    ) -> str:
        title = plan.objective.strip().rstrip(".")
        if artifact.kind == "presentation-outline":
            return self._presentation_outline(title)
        if artifact.kind == "drawing-concept":
            return self._drawing_concept(title)
        if artifact.kind == "report":
            return self._report_content(title)
        if artifact.kind == "script":
            return self._script_content(title)
        return json.dumps(plan.asdict(), indent=2)

    @staticmethod
    def _presentation_outline(title: str) -> str:
        return "\n".join(
            [
                "# Presentation Outline\n",
                f"Objective: {title}\n",
                "## Slide 1: Title",
                f"- {title}",
                "## Slide 2: Why This Matters",
                "- Problem statement",
                "- Desired outcome",
                "## Slide 3: Proposed Approach",
                "- Workflow summary",
                "- Key actions",
                "## Slide 4: Risks and Safeguards",
                "- Approval gates",
                "- Operator checkpoints",
                "## Slide 5: Next Steps",
                "- Execute",
                "- Review",
                "- Refine",
                "",
            ]
        )

    def _drawing_concept(self, title: str) -> str:
        return "\n".join(
            [
                (
                    '<svg xmlns="http://www.w3.org/2000/svg" '
                    'width="640" height="360" viewBox="0 0 640 360">'
                ),
                '  <rect width="640" height="360" fill="#f8f6ef" />',
                (
                    '  <path d="M 40 280 L 160 140 L 280 280 Z" '
                    'fill="none" stroke="#24424a" stroke-width="8" />'
                ),
                (
                    '  <text x="40" y="330" fill="#24424a" '
                    f'font-size="20">{self._xml_escape(title)}</text>'
                ),
                "</svg>",
                "",
            ]
        )

    @staticmethod
    def _report_content(title: str) -> str:
        return "\n".join(
            [
                f"# {title}",
                "",
                "## Summary",
                (f"This document was generated as a starter report for: {title}."),
                "",
                "## Main Points",
                "- Objective received through AgentOS workflow channel.",
                ("- Guarded desktop execution can now open an app and continue work."),
                ("- Operator approval remains required for live OS actions."),
                "",
                "## Next Steps",
                "1. Review the structure.",
                "2. Expand the content.",
                "3. Export to the target application if needed.",
                "",
            ]
        )

    @staticmethod
    def _script_content(title: str) -> str:
        purpose = title.replace('"', "'")
        return "\n".join(
            [
                '"""Starter automation script generated by AgentOS."""',
                "",
                "from __future__ import annotations",
                "",
                "",
                "def main() -> None:",
                f'    """Goal: {purpose}."""',
                ('    print("Replace this starter logic with the real workflow.")'),
                "",
                "",
                'if __name__ == "__main__":',
                "    main()",
                "",
            ]
        )

    @staticmethod
    def _xml_escape(value: str) -> str:
        return (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
